= INPUT
Sensor at x=2, y=18: closest beacon is at x=-2, y=15
Sensor at x=9, y=16: closest beacon is at x=10, y=16
Sensor at x=13, y=2: closest beacon is at x=15, y=3
Sensor at x=12, y=14: closest beacon is at x=10, y=16
Sensor at x=10, y=20: closest beacon is at x=10, y=16
Sensor at x=14, y=17: closest beacon is at x=10, y=16
Sensor at x=8, y=7: closest beacon is at x=2, y=10
Sensor at x=2, y=0: closest beacon is at x=2, y=10
Sensor at x=0, y=11: closest beacon is at x=2, y=10
Sensor at x=20, y=14: closest beacon is at x=25, y=17
Sensor at x=17, y=20: closest beacon is at x=21, y=22
Sensor at x=16, y=7: closest beacon is at x=15, y=3
Sensor at x=14, y=3: closest beacon is at x=15, y=3
Sensor at x=20, y=1: closest beacon is at x=15, y=3

= APPROACHES
== 1: system of inequations
=== Derived rules
0 <= x 
x <= 20
0 <= y
y <= 20
abs(x - 2) + abs(y - 18) > 7
abs(x - 9) + abs(y - 16) > 1
abs(x - 13) + abs(y - 2) > 3
abs(x - 12) + abs(y - 14) > 4
abs(x - 10) + abs(y - 20) > 4
abs(x - 14) + abs(y - 17) > 5
abs(x - 8) + abs(y - 7) > 9
abs(x - 2) + abs(y - 0) > 14
abs(x - 0) + abs(y - 11) > 3
abs(x - 20) + abs(y - 14) > 8
abs(x - 17) + abs(y - 20) > 6
abs(x - 16) + abs(y - 7) > 5
abs(x - 14) + abs(y - 3) > 1
abs(x - 20) + abs(y - 1) > 7

abs(x) <= 20
abs(y) <= 20

== 2 resolve it
from constraint import *
p = Problem()
p.addVariable("x", range(0,21))
p.addVariable("y", range(0,21))
p.addConstraint(abs(x - 2) + abs(y - 18) > 7, ("x","y"))
p.addConstraint(abs(x - 9) + abs(y - 16) > 1, ("x","y"))
p.addConstraint(abs(x - 13) + abs(y - 2) > 3, ("x","y"))
p.addConstraint(abs(x - 12) + abs(y - 14) > 4, ("x","y"))
p.addConstraint(abs(x - 10) + abs(y - 20) > 4, ("x","y"))
p.addConstraint(abs(x - 14) + abs(y - 17) > 5, ("x","y"))
p.addConstraint(abs(x - 8) + abs(y - 7) > 9, ("x","y"))
p.addConstraint(abs(x - 2) + abs(y - 0) > 14, ("x","y"))
p.addConstraint(abs(x - 0) + abs(y - 11) > 3, ("x","y"))
p.addConstraint(abs(x - 20) + abs(y - 14) > 8, ("x","y"))
p.addConstraint(abs(x - 17) + abs(y - 20) > 6, ("x","y"))
p.addConstraint(abs(x - 16) + abs(y - 7) > 5, ("x","y"))
p.addConstraint(abs(x - 14) + abs(y - 3) > 1, ("x","y"))
p.addConstraint(abs(x - 20) + abs(y - 1) > 7, ("x","y"))
res = p.getSolutions()
print(res)

== 3 new / modified idea
=== Motivation
approach 1/2 works per se, but is too slow

=== approach
* use variables dist_x_i and dist_y_i for each sensor i
* use MinSumConstraints: dist_x_i + dist_y_i > range_i
* use constraints for x and y; dist_x_i = |x-delta_x_i| => x  

=== draft
from constraint import *
p = Problem()
p.addVariable("x", range(0,21))
p.addVariable("y", range(0,21))
# sensor 1
p.addVariable("abs_delta_x_1", range(0, 21))
p.addVariable("abs_delta_y_1", range(0, 21))
p.addConstraint(abs_delta_x_1 + abs_delta_y_1 > 7, ("abs_delta_x_1", "abs_delta_y_1"))
p.addContraint(??? how does x depend on abs_delta_x_1 for abs_delta_x_1 = abs(x - delta_x_1) = |x - 2)
   => (x >= delta_x_1 and x - delta_x_1 == abs_delta_x_1) or (x < delta_x_1 and (-x - delta_x_1) == abs_delta_x_1)
... etc.
res = p.getSolutions()
print(res)

