[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Frank Schmitt <frankschmitt@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cute = "0.3.0"
regex = "1.4.2"
petgraph = "0.5.1"